version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
    tty: true
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/app
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8000:80"

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8200:80"
    environment:
      - PMA_ARBITRARY=1

